# Generated by Django 5.1.2 on 2024-10-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_missions', '0002_remove_dailymission_mission_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymission',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
