# Generated by Django 5.1.2 on 2024-10-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_missions', '0004_remove_dailymission_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymission',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
