# Generated by Django 5.1.2 on 2024-10-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_missions', '0005_alter_dailymission_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dailymission',
            name='updated_at',
        ),
    ]
