# Generated by Django 5.1.2 on 2024-10-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_name_imagepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_type',
            field=models.CharField(choices=[('text', 'Text Only'), ('image', 'Image Only')], default='text', max_length=10),
        ),
    ]
