# Generated by Django 5.1.2 on 2024-10-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_board_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
